#pragma once

#include <SFML\Audio.hpp>
#include <SFML\Config.hpp>
#include <SFML\GpuPreference.hpp>
#include <SFML\Graphics.hpp>
#include <SFML\Main.hpp>
#include <SFML\Network.hpp>
#include <SFML\OpenGL.hpp>
#include <SFML\System.hpp>
#include <SFML\Window.hpp>
#include "AudioSource.h"
#include "Button.h"
#include "ButtonObject.h"
#include "Camera2D.h"
#include "CameraObject2D.h"
#include "Component.h"
#include "Context.h"
#include "Engine.h"
#include "Event.h"
#include "EventHandler.h"
#include "FontResource.h"
#include "GameObject.h"
#include "InputManager.h"
#include "Point2D.h"
#include "Renderer2D.h"
#include "Resource.h"
#include "ResourceManager.h"
#include "Scene.h"
#include "SceneManager.h"
#include "Selectable.h"
#include "SoundResource.h"
#include "State.h"
#include "StateCondition.h"
#include "StateMachine.h"
#include "StateTransition.h"
#include "TextObject.h"
#include "Text.h"
#include "TextureResource.h"
#include "TimeManager.h"
#include "PointObject2D.h"
#include "BoxCollider2D.h"