#pragma once

#include <iostream>
#include <vector>
#include <unordered_map>
#include <string>
#include <SFML\Graphics.hpp>
#include <SFML\Audio.hpp>
#include <SFML\Network.hpp>
#include <SFML\System.hpp>
#include <SFML\Window.hpp>
#include <SFML\Config.hpp>
#include <SFML\GpuPreference.hpp>
#include <SFML\Main.hpp>
#include <SFML\OpenGL.hpp>
#include <algorithm>
#include <future>
#include <cmath>
#include <queue>